# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_auto_20180208_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='quotes_app.Favorite'),
        ),
    ]
