# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_auto_20180208_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes_app.User'),
        ),
    ]
