# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favoring_users',
            field=models.ManyToManyField(related_name='fav_quotes', to='project1_app.User'),
        ),
    ]
