# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakeUserForm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
    ]
