# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-27 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakeUserForm_app', '0002_auto_20180126_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='allias',
        ),
    ]
