# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='decription',
            new_name='description',
        ),
    ]
